### ISSUE TITLE
error when deleting file currently being viewed

### ISSUE THREAD

**Issue by pmuellr** [pmuellr/md-viewer#16]
upon deletion, a prompter appears with the title "**A JavaScript error occured in the browser process**", followed by the stack trace:

```
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/pmuellr/Projects/SECRET.md'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:399:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
    at Object.render (....app/Contents/Resources/app/main/markdown.js:25:23)
    at Viewer.reload (....app/Contents/Resources/app/main/viewers.js:131:14)
    at Viewer.fileModified (....app/Contents/Resources/app/main/viewers.js:143:10)
    at StatWatcher.<anonymous> (....app/Contents/Resources/app/main/viewers.js:125:12)
    at emitTwo (events.js:87:13)
```

**Comment by pmuellr** [comment]
suggest we have a fail mode for opening a file which doesn't exist - display some static text - "file not found" or some such.  Including the file name would probably be nice, perhaps stat'ing in case the file exists cannot be read, etc.
